[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MEDS_polars_functions"
dynamic = ["version"]
authors = [
  { name="Matthew McDermott", email="mattmcdermott8@gmail.com" },
]
description = "MEDS ETL and transformation functions leveraging a sharding-based parallelism model & polars."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["polars>=1.1.0", "pyarrow", "nested_ragged_tensors", "loguru", "hydra-core", "numpy"]

[tool.setuptools_scm]

[project.optional-dependencies]
examples = ["rootutils"]
dev = ["pre-commit"]
tests = ["pytest", "pytest-cov", "rootutils"]
local_parallelism = ["hydra-joblib-launcher"]
slurm_parallelism = ["hydra-submitit-launcher"]

[project.scripts]
MEDS_extract-split_and_shard_patients = "MEDS_polars_functions.extraction.split_and_shard_patients:main"
MEDS_extract-shard_events = "MEDS_polars_functions.extraction.shard_events:main"
MEDS_extract-convert_to_sharded_events = "MEDS_polars_functions.extraction.convert_to_sharded_events:main"
MEDS_extract-merge_to_MEDS_cohort = "MEDS_polars_functions.extraction.merge_to_MEDS_cohort:main"
MEDS_transform-aggregate_code_metadata = "MEDS_polars_functions.aggregate_code_metadata:main"

[project.urls]
Homepage = "https://github.com/mmcdermott/MEDS_polars_functions"
Issues = "https://github.com/mmcdermott/MEDS_polars_functions/issues"
