defaults:
  - pipeline

# The event conversion configuration file is used throughout the pipeline to define the events to extract.
event_conversion_config_fp: ???

stages:
  - shard_events
  - split_and_shard_patients
  - convert_to_sharded_events
  - merge_to_MEDS_cohort

stage_configs:
  shard_events:
    row_chunksize: 200000000
    infer_schema_length: 10000
  split_and_shard_patients:
    is_metadata: True
    output_dir: ${cohort_dir}
    n_patients_per_shard: 50000
    external_splits_json_fp: null
    split_fracs:
      train: 0.8
      tuning: 0.1
      held_out: 0.1
  merge_to_MEDS_cohort:
    output_dir: ${cohort_dir}/final_cohort
