defaults:
  - pipeline

# Pipeline Structure
stages:
  - shard_by_event
  - generate_patient_shards
  - convert_to_MEDS_and_subshard
  - merge_subshards

# Event Conversion
event_conversion_config_fp: ???

# Splits
external_splits_json_fp: null
split_fracs:
  train: 0.8
  tuning: 0.1
  held_out: 0.1

# Sharding
row_chunksize: 200000000
n_patients_per_shard: 50000
infer_schema_length: 10000
