# Global IO
input_dir: ???
cohort_dir: ???

log_dir: "${cohort_dir}/.logs/${stage}/worker_${worker}/${now:%Y-%m-%d_%H-%M-%S}"

# General pipeline variables
do_overwrite: False
seed: 1
stages: ??? # The list of stages to this overall pipeline

# Mapreduce information
worker: 1
polling_time: 300 # wait time in seconds before beginning reduction steps

# Filling in the current stage
stage: ${current_script_name:}
stage_cfg: ${oc.create:${populate_stage:${stage}}}

# Hydra
hydra:
  job:
    name: "${stage}"
  run:
    dir: "${log_dir}/${hydra.job.name}"
  sweep:
    dir: "${log_dir}/${hydra.job.name}"
