defaults:
  - pipeline

# Pipeline Structure
stages:
  - filter_patients_by_length
  - add_time_derived_measurements
  - preliminary_counts
  - filter_codes
  - fit_outlier_detection
  - filter_outliers
  - fit_normalization
  - normalization
  - tokenization
  - tensorization

stages:
  filter_patients_by_length:
    input_dir: ???
    output_dir: ???
    min_events_per_patient: null
    min_measurements_per_patient: null

  add_time_derived_measurements
  preliminary_counts
  filter_codes
  fit_outlier_detection
  filter_outliers
  fit_normalization
  normalization
  tokenization
  tensorization


# Filtering parameters
min_code_occurrences: null
min_events_per_patient: null
min_measurements_per_patient: null

# Time-derived measurements
time_derived_measurements:
  age:
    dob_code: ???
    age_code: "AGE"
    age_unit: "years"
  time_of_day:
    bin_endpoints: [6, 12, 18, 24]

# Code modifiers will be used as adjoining parts of the `code` columns during group-bys and eventual
# tokenization.
code_modifier_columns: ???

# Code metadata extraction. These may contain duplicates because the data may be filtered between different
# stages, depending on the pipeline in question.
code_processing_stages:
  preliminary_counts:
    - "code/n_occurrences"
    - "code/n_patients"
  fit_outlier_detection:
    - "values/n_occurrences"
    - "values/sum"
    - "values/sum_sqd"
  fit_normalization:
    - "code/n_occurrences"
    - "code/n_patients"
    - "values/n_occurrences"
    - "values/sum"
    - "values/sum_sqd"

# Outlier detection
outlier_stddev_cutoff: 4.5
